import type { languages } from 'monaco-editor';

// ── .airo Code Snippets for Monaco Editor ────────────────────────
// Derived from the VS Code extension snippets

export const airoSnippets: languages.CompletionItem[] = [
  {
    label: 'robot',
    kind: 15, // Snippet
    documentation: 'Create a new robot template with SENSE → THINK → ACT loop',
    insertText: [
      '# ============================================',
      '# ${1:Robot Name} - ${2:Description}',
      '# ============================================',
      '',
      '#library#',
      '# Import body modules for your robot',
      '# call body/actuation/hands.airo.',
      '# call body/sight/eyes.airo.',
      '# call body/hearing/ears.airo.',
      '',
      'pin defi {',
      '    ${3:ledpin} = ${4:2}; ${5|output,input|}.',
      '}',
      '',
      '#variables#',
      'brain_url = "${6:wss://brain.local:8080}".',
      'call brain_url.',
      '',
      'loop {',
      '    # SENSE',
      '    read_for(${7:1000}) {',
      '        ${8:# sensor_name.}',
      '    }',
      '',
      '    # THINK',
      '    senddatato(brain_url).',
      '',
      '    # ACT',
      '    actfor(${9:1000}) {',
      '        ${3:ledpin}.',
      '    }',
      '}',
    ].join('\n'),
    insertTextRules: 4, // InsertAsSnippet
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'pin',
    kind: 15,
    documentation: 'Define hardware pins for your robot',
    insertText: [
      'pin defi {',
      '    ${1:pin_name} = ${2:2}; ${3|output,input|}.',
      '}',
    ].join('\n'),
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'read_for',
    kind: 15,
    documentation: 'Read sensors for specified duration (milliseconds)',
    insertText: [
      'read_for(${1:1000}) {',
      '    ${2:sensor_name}.',
      '}',
    ].join('\n'),
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'actfor',
    kind: 15,
    documentation: 'Control actuators for specified duration (milliseconds)',
    insertText: [
      'actfor(${1:1000}) {',
      '    ${2:output_name}.',
      '}',
    ].join('\n'),
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'senddatato',
    kind: 15,
    documentation: 'Send sensor data to AI brain',
    insertText: 'senddatato(${1:brain_url}).',
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'loop',
    kind: 15,
    documentation: 'Main robot loop',
    insertText: ['loop {', '    ${1:// robot logic}', '}'].join('\n'),
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'if',
    kind: 15,
    documentation: 'Conditional statement',
    insertText: ['if (${1:condition}) {', '    ${2:// action}', '}'].join('\n'),
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'ifelse',
    kind: 15,
    documentation: 'Conditional with else branch',
    insertText: [
      'if (${1:condition}) {',
      '    ${2:// action}',
      '} else {',
      '    ${3:// alternative}',
      '}',
    ].join('\n'),
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'init',
    kind: 15,
    documentation: 'Initialization block (runs once at startup)',
    insertText: ['init {', '    ${1:// initialization code}', '}'].join('\n'),
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'brain',
    kind: 15,
    documentation: 'Set up AI brain WebSocket connection',
    insertText: [
      '# Brain connection',
      'brain_url = "${1:wss://brain.local:8080}".',
      'call brain_url.',
    ].join('\n'),
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'ask',
    kind: 15,
    documentation: 'Ask the AI brain a question',
    insertText: 'ask(${1:brain_url}, ${2:"question"}).',
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'saveto',
    kind: 15,
    documentation: 'Save data to a destination',
    insertText: 'saveto(${1:destination}).',
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
  {
    label: 'call',
    kind: 15,
    documentation: 'Import a body module or invoke a variable',
    insertText: 'call ${1:body/module.airo}.',
    insertTextRules: 4,
    range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 } as any,
  },
];

// ── Autocomplete keywords ────────────────────────────────────────

export const airoKeywordCompletions: languages.CompletionItem[] = [
  { label: 'pin', kind: 14, insertText: 'pin', documentation: 'Pin declaration keyword' },
  { label: 'defi', kind: 14, insertText: 'defi', documentation: 'Pin definition block' },
  { label: 'if', kind: 14, insertText: 'if', documentation: 'Conditional statement' },
  { label: 'else', kind: 14, insertText: 'else', documentation: 'Else branch' },
  { label: 'loop', kind: 14, insertText: 'loop', documentation: 'Main robot loop' },
  { label: 'read_for', kind: 14, insertText: 'read_for', documentation: 'Read sensors for duration' },
  { label: 'senddatato', kind: 14, insertText: 'senddatato', documentation: 'Send data to AI brain' },
  { label: 'actfor', kind: 14, insertText: 'actfor', documentation: 'Control actuators for duration' },
  { label: 'call', kind: 14, insertText: 'call', documentation: 'Import module / invoke variable' },
  { label: 'ask', kind: 14, insertText: 'ask', documentation: 'Ask AI brain a question' },
  { label: 'saveto', kind: 14, insertText: 'saveto', documentation: 'Save data to destination' },
  { label: 'init', kind: 14, insertText: 'init', documentation: 'Initialization block' },
  { label: 'input', kind: 20, insertText: 'input', documentation: 'Pin input mode' },
  { label: 'output', kind: 20, insertText: 'output', documentation: 'Pin output mode' },
  { label: 'read', kind: 14, insertText: 'read', documentation: 'Read sensor value' },
];
